export const array = [
  [
    {
      dataru: 'ё',
      dataeng: '`',
      shiftedRu: 'Ё',
      shiftedEng: '~',
      capsLockRu: 'Ё',
    },
    {
      dataru: '1',
      dataeng: '1',
      shiftedRu: '!',
      shiftedEng: '!',
    },
    {
      dataru: '2',
      dataeng: '2',
      shiftedRu: '"',
      shiftedEng: '@',
    },
    {
      dataru: '3',
      dataeng: '3',
      shiftedRu: '№',
      shiftedEng: '#',
    },
    {
      dataru: '4',
      dataeng: '4',
      shiftedRu: ';',
      shiftedEng: '$',
    },
    {
      dataru: '5',
      dataeng: '5',
      shiftedRu: '%',
      shiftedEng: '%',
    },
    {
      dataru: '6',
      dataeng: '6',
      shiftedRu: ':',
      shiftedEng: '^',
    },
    {
      dataru: '7',
      dataeng: '7',
      shiftedRu: '?',
      shiftedEng: '&',
    },
    {
      dataru: '8',
      dataeng: '8',
      shiftedRu: '*',
      shiftedEng: '*',
    },
    {
      dataru: '9',
      dataeng: '9',
      shiftedRu: '(',
      shiftedEng: '(',
    },
    {
      dataru: '0',
      dataeng: '0',
      shiftedRu: ')',
      shiftedEng: ')',
    },
    {
      dataru: '-',
      dataeng: '-',
      shiftedRu: '_',
      shiftedEng: '_',
    },
    {
      dataru: '=',
      dataeng: '=',
      shiftedRu: '+',
      shiftedEng: '+',
    },
    {
      dataru: 'Backspace',
      dataeng: 'Backspace',
    },
  ],
  [
    {
      dataru: 'Tab',
      dataeng: 'Tab',
    },
    {
      dataru: 'й',
      dataeng: 'q',
      shiftedRu: 'Й',
      shiftedEng: 'Q',
      capsLockRu: 'Й',
      capsLockEng: 'Q',
    },
    {
      dataru: 'ц',
      dataeng: 'w',
      shiftedRu: 'Ц',
      shiftedEng: 'W',
      capsLockRu: 'Ц',
      capsLockEng: 'W',
    },
    {
      dataru: 'у',
      dataeng: 'e',
      shiftedRu: 'У',
      shiftedEng: 'E',
      capsLockRu: 'У',
      capsLockEng: 'E',
    },
    {
      dataru: 'к',
      dataeng: 'r',
      shiftedRu: 'К',
      shiftedEng: 'R',
      capsLockRu: 'К',
      capsLockEng: 'R',
    },
    {
      dataru: 'е',
      dataeng: 't',
      shiftedRu: 'Е',
      shiftedEng: 'T',
      capsLockRu: 'Е',
      capsLockEng: 'T',
    },
    {
      dataru: 'н',
      dataeng: 'y',
      shiftedRu: 'Н',
      shiftedEng: 'Y',
      capsLockRu: 'Н',
      capsLockEng: 'Y',
    },
    {
      dataru: 'г',
      dataeng: 'u',
      shiftedRu: 'Г',
      shiftedEng: 'U',
      capsLockRu: 'Г',
      capsLockEng: 'U',
    },
    {
      dataru: 'ш',
      dataeng: 'i',
      shiftedRu: 'Ш',
      shiftedEng: 'I',
      capsLockRu: 'Ш',
      capsLockEng: 'I',
    },
    {
      dataru: 'щ',
      dataeng: 'o',
      shiftedRu: 'Щ',
      shiftedEng: 'O',
      capsLockRu: 'Щ',
      capsLockEng: 'O',
    },
    {
      dataru: 'з',
      dataeng: 'p',
      shiftedRu: 'З',
      shiftedEng: 'P',
      capsLockRu: 'З',
      capsLockEng: 'P',
    },
    {
      dataru: 'х',
      dataeng: '[',
      shiftedRu: 'Х',
      shiftedEng: '{',
      capsLockRu: 'Х',
    },
    {
      dataru: 'ъ',
      dataeng: ']',
      shiftedRu: 'Ъ',
      shiftedEng: '}',
      capsLockRu: 'Ъ',
    },
    {
      dataru: String.fromCharCode(92),
      dataeng: String.fromCharCode(92),
      shiftedRu: '/',
      shiftedEng: '|',
    },
    {
      dataru: 'Delete',
      dataeng: 'Delete',
    },
  ],
  [
    {
      dataru: 'CapsLock',
      dataeng: 'CapsLock',
    },
    {
      dataru: 'ф',
      dataeng: 'a',
      shiftedRu: 'Ф',
      shiftedEng: 'A',
      capsLockRu: 'Ф',
      capsLockEng: 'A',
    },
    {
      dataru: 'ы',
      dataeng: 's',
      shiftedRu: 'Ы',
      shiftedEng: 'S',
      capsLockRu: 'Ы',
      capsLockEng: 'S',
    },
    {
      dataru: 'в',
      dataeng: 'd',
      shiftedRu: 'В',
      shiftedEng: 'D',
      capsLockRu: 'В',
      capsLockEng: 'D',
    },
    {
      dataru: 'а',
      dataeng: 'f',
      shiftedRu: 'А',
      shiftedEng: 'F',
      capsLockRu: 'А',
      capsLockEng: 'F',
    },
    {
      dataru: 'п',
      dataeng: 'g',
      shiftedRu: 'П',
      shiftedEng: 'G',
      capsLockRu: 'П',
      capsLockEng: 'G',
    },
    {
      dataru: 'р',
      dataeng: 'h',
      shiftedRu: 'Р',
      shiftedEng: 'H',
      capsLockRu: 'Р',
      capsLockEng: 'H',
    },
    {
      dataru: 'о',
      dataeng: 'j',
      shiftedRu: 'О',
      shiftedEng: 'J',
      capsLockRu: 'О',
      capsLockEng: 'J',
    },
    {
      dataru: 'л',
      dataeng: 'k',
      shiftedRu: 'Л',
      shiftedEng: 'K',
      capsLockRu: 'Л',
      capsLockEng: 'K',
    },
    {
      dataru: 'д',
      dataeng: 'l',
      shiftedRu: 'Д',
      shiftedEng: 'L',
      capsLockRu: 'Д',
      capsLockEng: 'L',
    },
    {
      dataru: 'ж',
      dataeng: ';',
      shiftedRu: 'Ж',
      shiftedEng: ':',
      capsLockRu: 'Ж',
    },
    {
      dataru: 'э',
      dataeng: String.fromCharCode(39),
      shiftedRu: 'Э',
      shiftedEng: '"',
      capsLockRu: 'Э',
    },
    {
      dataru: 'Enter',
      dataeng: 'Enter',
    },
  ],
  [
    {
      dataru: 'Shift',
      dataeng: 'Shift',
    },
    {
      dataru: 'я',
      dataeng: 'z',
      shiftedRu: 'Я',
      shiftedEng: 'Z',
      capsLockRu: 'Я',
      capsLockEng: 'Z',
    },
    {
      dataru: 'ч',
      dataeng: 'x',
      shiftedRu: 'Ч',
      shiftedEng: 'X',
      capsLockRu: 'Ч',
      capsLockEng: 'X',
    },
    {
      dataru: 'с',
      dataeng: 'c',
      shiftedRu: 'С',
      shiftedEng: 'C',
      capsLockRu: 'С',
      capsLockEng: 'C',
    },
    {
      dataru: 'м',
      dataeng: 'v',
      shiftedRu: 'М',
      shiftedEng: 'V',
      capsLockRu: 'М',
      capsLockEng: 'V',
    },
    {
      dataru: 'и',
      dataeng: 'b',
      shiftedRu: 'И',
      shiftedEng: 'B',
      capsLockRu: 'И',
      capsLockEng: 'B',
    },
    {
      dataru: 'т',
      dataeng: 'n',
      shiftedRu: 'Т',
      shiftedEng: 'N',
      capsLockRu: 'Т',
      capsLockEng: 'N',
    },
    {
      dataru: 'ь',
      dataeng: 'm',
      shiftedRu: 'Ь',
      shiftedEng: 'M',
      capsLockRu: 'Ь',
      capsLockEng: 'M',
    },
    {
      dataru: 'б',
      dataeng: ',',
      shiftedRu: 'Б',
      shiftedEng: '<',
      capsLockRu: 'Б',
    },
    {
      dataru: 'ю',
      dataeng: '.',
      shiftedRu: 'Ю',
      shiftedEng: '>',
      capsLockRu: 'Ю',
    },
    {
      dataru: '.',
      dataeng: '/',
      shiftedRu: ',',
      shiftedEng: '?',
    },
    {
      dataru: '▲',
      dataeng: '▲',
    },
    {
      dataru: 'Shift',
      dataeng: 'Shift',
    },
  ],
  [
    {
      dataru: 'Control',
      dataeng: 'Control',
    },
    {
      dataru: 'Win',
      dataeng: 'Win',
    },
    {
      dataru: 'Alt',
      dataeng: 'Alt',
    },
    {
      dataru: 'Space',
      dataeng: 'Space',
    },
    {
      dataru: 'Alt',
      dataeng: 'Alt',
    },
    {
      dataru: '◄',
      dataeng: '◄',
    },
    {
      dataru: '▼',
      dataeng: '▼',
    },
    {
      dataru: '►',
      dataeng: '►',
    },
    {
      dataru: 'Control',
      dataeng: 'Control',
    },
  ],
];
